enter/urls.py
from django.urls import path

from . import views

app_name = 'enter'

urlpatterns = [
    path('', views.screen_category, name='screen_category'),   
    path('add category/', views.add_category, name='add_category'),
    
    path('all equipments/', views.screen_equipment, name='screen_equipment'),   
    path('details equipment/<int:id>/', views.details_equipment, name='details_equipment'),
    path('add equipment/', views.add_equipment, name='add_equipment'),

    path('all equipments out/', views.screen_equipmentOut, name='screen_equipmentOut'),
    path('details equipment out/<int:id>/', views.details_equipmentOut, name='details_equipmentOut'),
    path('add equipment out/', views.add_equipmentOut, name='add_equipmentOut'),

    path('history/', views.screen_history, name='screen_history'),
    
    path('export json/', views.export_data_as_json, name='export_data_as_json'),
    path('export json number/<int:id>/', views.export_data_as_json_by_id, name='export_data_as_json_id'),
    path('export json text/', views.export_data_as_json_into_text, name='export_data_as_json_into_text'),
    
    #path('update element/<int:id>/', views.update_element, name='update_element'),
    #path('choice element/', views.choice_element, name='choice_element'),
    #path('update equipment/<int:id>/', views.update_equipment, name='update_equipment'), 
    #path('delete equipment/<int:id>/', views.delete_equipment, name='delete_equipment'), 
    #path('', views.get_equipment, name='get_equipment'),
    #path('load serie/', views.load_serie, name='load_serie'),
    #path('graphic/', views.graphic, name='graphic'),
    #path('routeur/', views.routeur, name='routeur'), 
    #path('state/', views.state, name='state'),
    #path('routeur/', views.routeur, name='routeur'), 
    #path('new routeur/', views.new_routeur, name='new_routeur'),
    #path('search equipment/', views.search_equipment, name='search_equipment'), 
]

store_manage/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('helper/', admin.site.urls),
    path('', include('enter.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

enter/models.py
from django.db import models
from django.contrib.auth.models import User

#from django.utils.text import slugify
from django.dispatch import receiver
from django.db.models.signals import pre_save, post_save

# Create your models here.

class Category(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100, unique=True, verbose_name="Title")
    description = models.TextField(blank=True, verbose_name="Description")
    number = models.IntegerField(blank=True, default=0, verbose_name="Quantity_of_equipment")
    image = models.ImageField(upload_to='enter_category/', blank=True, null=True)

    class Meta:
        verbose_name = "Category_Equipment"

    def __str__(self):
        return self.title
    

class Equipment(models.Model):
    id = models.AutoField(primary_key=True)
    serialNumber = models.CharField(max_length=100)
    description = models.CharField(max_length=100, unique=False, verbose_name="Name_of_equipment")
    quantity = models.IntegerField(blank=True, default=1)
    supplier = models.CharField(max_length=100)
    cost = models.IntegerField()
    last_update = models.DateTimeField(auto_now=True, verbose_name="update_equipment")
    created_on = models.DateField(auto_now_add=True, verbose_name="created_equipment")
    classed = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Category_of_equipment")
    state = models.BooleanField(default=True)
    image = models.ImageField(upload_to='enter_equipment/', blank=True, null=True)

    class Meta:
        verbose_name = "Equipment stored"

    def __str__(self):
        return self.description
    

class Equipment_Out(models.Model):
    id = models.AutoField(primary_key=True)
    serialNumber = models.CharField(max_length=100)
    description = models.CharField(max_length=100, unique=False, verbose_name="Name_of_equipment")
    projet = models.CharField(max_length=100, unique=False, verbose_name="Projet_of_equipment")
    quantity = models.IntegerField(blank=True, default=1)
    last_update = models.DateTimeField(auto_now=True, verbose_name="update_equipment")
    created_on = models.DateField(auto_now=True, verbose_name="created_equipment")
    classed = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Category_of_equipment")
    equipment_in = models.ForeignKey(Equipment, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="equipment_in_stock")
    image = models.ImageField(upload_to='enter_equipmentOut/', blank=True, null=True)

    class Meta:
        verbose_name = "Equipment_Out"

    def __str__(self):
        return self.description
    
@receiver(post_save, sender=Equipment)
def update_Category_number(sender, instance, **kwargs):
    instance.classed.number += 1
    instance.classed.save()

class ActionHistory(models.Model): 
    user = models.ForeignKey(User, on_delete=models.CASCADE) 
    action = models.CharField(max_length=100) 
    timestamp = models.DateField(auto_now=True, verbose_name="created_equipement")

    class Meta:
        verbose_name = "History"

    def __str__(self):
        return f"{self.user.username} - {self.action} at {self.timestamp}"

    

enter/forms.py
from django import forms

from .models import Category, Equipment, Equipment_Out

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('title', 'description', 'image')

    choices_c = [("routeur", "Routeur"), ("cable", "Cable"), ("pc", "Pc"), ("switch", "Switch")]
    title = forms.ChoiceField(choices = choices_c, widget=forms.Select(attrs={
        'class': 'form-control',
    }))
    description = forms.CharField(required=False, widget=forms.Textarea)
    image = forms.ImageField(required=False, widget=forms.ClearableFileInput)


class EquipmentForm(forms.ModelForm):
    class Meta: 
        model = Equipment
        fields = ('serialNumber', 'description', 'supplier', 'cost', 'classed',)

    serialNumber = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    description = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
    })) 
    supplier = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    cost = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'form-control',
    }))
    classed = forms.ModelChoiceField(queryset=Category.objects.all(), label ="Category", widget=forms.Select)

    labels = {
        "classed": "Category",
    }


class EquipmentOutForm(forms.ModelForm):
    class Meta: 
        model = Equipment_Out
        fields = ('serialNumber', 'description', 'projet', 'classed',)

    classed = forms.ModelChoiceField(queryset=Category.objects.all(), widget=forms.Select)
    serialNumber = forms.ModelChoiceField(queryset=Equipment.objects.all(), widget=forms.Select)
    description = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
    })) 
    projet = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))

    labels = {
        "classed": "Category",
    }

enter/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .models import Category, Equipment, Equipment_Out, ActionHistory
from .forms import CategoryForm, EquipmentForm, EquipmentOutForm

from django.contrib.auth.decorators import login_required, user_passes_test

from django.core.paginator import Paginator
from django.utils import timezone

from django.http import JsonResponse
import json

# Create your views here.

# View for the action to screen

def screen_category(request):
    
    enter_category = Category.objects.all()

    context = {
        'equipments' : enter_category,
    }

    return render(request, "all_category.html", context)


#@user_passes_test(lambda u: "master" in [group.name for group in u.groups.all()])
def screen_equipment(request):
    
    enter_equipment = Equipment.objects.all()

    paginator = Paginator(enter_equipment, 6)
    
    page_number = request.GET.get('page')
    page_object = paginator.get_page(page_number)

    context = {
        'equipments' : page_object,
    }

    return render(request, "all_equipment.html", context)


#@user_passes_test(lambda u: "master" in [group.name for group in u.groups.all()])
def screen_equipmentOut(request):
    
    enter_equipmentOut = Equipment_Out.objects.all()

    paginator = Paginator(enter_equipmentOut, 6)
    
    page_number = request.GET.get('page')
    page_object = paginator.get_page(page_number)

    context = {
        'equipments' : page_object,
    }

    return render(request, "all_equipmentOut.html", context)


def screen_history(request):
    
    enter_history = ActionHistory.objects.all()

    context = {
        'equipments' : enter_history,
    }

    return render(request, "history.html", context)



# View for the action to details

def details_equipment(request, id):
    
    #details = Equipment.objects.get(number=number)
    details = get_object_or_404(Equipment, id=id)
    context = {
        'details' : details
    }
    
    return render(request, 'details_equipment.html', context)


def details_equipmentOut(request, id):
    
    #details = Equipment.objects.get(number=number)
    details = get_object_or_404(Equipment_Out, id=id)
    context = {
        'details' : details
    }
    
    return render(request, 'details_equipmentOut.html', context)



# View for the action to add

#@login_required
def add_category(request):
        
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            
            action = ActionHistory(user=request.user, action="input_category", timestamp=timezone.now())
            action.save()
            return redirect('enter:screen_category')
            
    else:
        form = CategoryForm()
        
    context = {
        'form': form,
    }

    return render(request, 'add_category.html', context)


#@login_required
def add_equipment(request):
        
    if request.method == 'POST':
        form = EquipmentForm(request.POST)
        if form.is_valid():
            form.save()

            action = ActionHistory(user=request.user, action="input_equipment", timestamp=timezone.now())
            action.save()
            
            return redirect('enter:screen_category')
   
    else:
        form = EquipmentForm()
        
    context = {
        'form': form,
    }
    return render(request, 'add_equipment.html', context)


#@login_required
def add_equipmentOut(request):
        
    if request.method == 'POST':
        form = EquipmentOutForm(request.POST)
        if form.is_valid():
            form.save()

            action = ActionHistory(user=request.user, action="output_equipment", timestamp=timezone.now())
            action.save()
            
            return redirect('enter:screen_category')
   
    else:
        form = EquipmentOutForm()
        
    context = {
        'form': form,
    }
    return render(request, 'add_equipmentOut.html', context)



# view to json

def export_data_as_json(request):
    data = list(Equipment.objects.values())
    return JsonResponse(data, safe=False)
 
def export_data_as_json_by_id(request, id):
    data = Equipment.objects.values('serialNumber', 'description', 'procurement', 'cost', 'created_on', 'state',).get(id=id)
    return JsonResponse(data, safe=False)

def export_data_as_json_into_text(request):
    data = list(Equipment.objects.values())
    with open('dataEquipmentlist.json', 'w') as file:
        json.dump(data, file)
    return JsonResponse({'message': 'Ok'})

enter/templates/add_category.html
{% extends 'storage/layouts/base.html' %}

{% block title %} Add category {% endblock %}
 
{% block body %}
    <div class="container">
        <br>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Mon site</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'enter:screen_category' %}">Home</a>
                    </li>
                </ul>
            </div>
        </nav>
        <br>

        <div class="row">
            <div class="col-md-8 mx-auto">
                <h4 class="text-center my-3">New</h4>
                <form action="" method="post">
                    {% if form.subject.errors %}
                        {% for error in form.subject.errors %}
                            <p class="text-danger"><strong>{{ error }}</strong></p>
                        {% endfor %}
                    {% endif %}
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}<br><br>
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <p class="text-danger"><strong>{{ error }}</strong></p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    {% endfor %}
                    <div class="col-12">
                        <button class="btn btn-primary mt-2" type="submit">submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock body %}

enter/templates/add_equipment.html
{% extends 'storage/layouts/base.html' %}

{% block title %} Add equipment {% endblock %}
 
{% block body %}
    <div class="container">
        <br>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Mon site</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'enter:screen_category' %}">Home</a>
                    </li>
                </ul>
            </div>
        </nav>
        <br>

        <div class="row">
            <div class="col-md-8 mx-auto">
                <h4 class="text-center my-3">New stock</h4>
                <form action="" method="post">
                    {% if form.subject.errors %}
                        {% for error in form.subject.errors %}
                            <p class="text-danger"><strong>{{ error }}</strong></p>
                        {% endfor %}
                    {% endif %}
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}<br>
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <p class="text-danger"><strong>{{ error }}</strong></p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    {% endfor %}
                    <div class="col-12">
                        <button class="btn btn-primary mt-2" type="submit">submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock body %}

enter/templates/add_equipmentOut.html
{% extends 'storage/layouts/base.html' %}

{% block title %} Add equipment out {% endblock %}
 
{% block body %}
    <div class="container">
        <br>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Mon site</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'enter:screen_category' %}">Home</a>
                    </li>
                </ul>
            </div>
        </nav>
        <br>

        <div class="row">
            <div class="col-md-8 mx-auto">
                <h4 class="text-center my-3">New Output</h4>
                <form action="" method="post">
                    {% if form.subject.errors %}
                        {% for error in form.subject.errors %}
                            <p class="text-danger"><strong>{{ error }}</strong></p>
                        {% endfor %}
                    {% endif %}
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}<br>
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <p class="text-danger"><strong>{{ error }}</strong></p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    {% endfor %}
                    <div class="col-12">
                        <button class="btn btn-primary mt-2" type="submit">submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock body %}

enter/templates/all_category.html
{% extends 'storage/layouts/base.html' %}

{% block title %} Category list {% endblock %}
 
{% block body %}
    <div class="container">    
        <br>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Mon site</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="#">home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'enter:add_category' %}">New Category</a>
                    </li>
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Storage
                      </a>
                      <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'enter:add_equipment' %}">Input</a></li>
                        <li><a class="dropdown-item" href="{% url 'enter:add_equipmentOut' %}">Output</a></li>
                      </ul>
                    </li>
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Inventory
                      </a>
                      <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'enter:screen_equipment' %}">Input</a></li>
                        <li><a class="dropdown-item" href="{% url 'enter:screen_equipmentOut' %}">Output</a></li>
                      </ul>
                    </li>
                </ul>
            </div>
        </nav>

        <br>

        <h2 class="mt-3">{{ message }}</h2>
        
        <div class="row row-cols-1 row-cols-md-2 g-4">
            {% for equipment in equipments %}
                <div class="col">
                    <div class="card mb-3" style="width: 32rem;">
                        {% if equipment.image %}
                            <img src="{{ equipment.image.url }}" class="card-img-top style=width: 28rem" alt="...">
                        {% endif %}
                        <div class="card-body">
                            <p class="card-title">{{ equipment.title }}</p>
                            <h5 class="card-title">{{ equipment.number }} {{ equipment.description }}</h5>
                            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                            <p class="card-text"><small class="text-body-secondary">Last updated 3 mins ago</small></p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block footer %}

{% endblock %}

enter/templates/all_equipment.html
{% extends 'storage/layouts/base.html' %}

{% block title %} Equipments list {% endblock %}
 
{% block body %}
        <div class="container"> 
            <br>
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <a class="navbar-brand" href="#">Mon site</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'enter:screen_category' %}">Home</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            <br>
            <br>
            <h2 class="mt-3"> {{ message }} </h2>
            
            <table class="table table-hover table-bordered">
                <thead>
                    <tr>
                        <th>N</th>
                        <th>serial number</th>
                        <th>description</th>
                        <th>date</th>
                        <th>statut</th>
                        <th>action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for equipment in equipments %}
                    <tr>
                        <td>{{ equipment.id }}</td>
                        <td><a class="nav-link" href="{% url 'enter:details_equipment' equipment.id %}">{{ equipment.serialNumber }}</a></td>
                        <td>{{ equipment.description }}</td>
                        <td>{{ equipment.created_on|date:"D F Y" }}</td>
                        <td>{{ equipment.state }}</td>
                        <td><a class="nav-link" href="{% url 'enter:details_equipment' equipment.id %}">📄</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
{% endblock %}

{% block footer %}

    <ul class="pagination justify-content-center">
        {% if equipments.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ equipments.previous_page_number }}">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}
        <li class="page-item">
            <p class="page-link text-muted">
                Page {{ equipments.number }} of {{ equipments.paginator.num_pages }}.
            </p>
        </li>
        {% if equipments.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ equipments.next_page_number }}">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>

{% endblock %}

enter/templates/all_equipmentOut.html
{% extends 'storage/layouts/base.html' %}

{% block title %} Equipments Out list {% endblock %}
 
{% block body %}
        <div class="container"> 
            <br>
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <a class="navbar-brand" href="#">Mon site</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'enter:screen_category' %}">Home</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            <br>
            <br>
            <h2 class="mt-3"> {{ message }} </h2>
            
            <table class="table table-hover table-bordered">
                <thead>
                    <tr>
                        <th>N</th>
                        <th>serial number</th>
                        <th>description</th>
                        <th>date</th>
                        <th>action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for equipment in equipments %}
                    <tr>
                        <td>{{ equipment.id }}</td>
                        <td><a class="nav-link" href="{% url 'enter:details_equipmentOut' equipment.id %}">{{ equipment.serialNumber }}</a></td>
                        <td>{{ equipment.description }}</td>
                        <td>{{ equipment.created_on }}</td>
                        <td><a class="nav-link" href="{% url 'enter:details_equipmentOut' equipment.id %}">📄</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
{% endblock %}

{% block footer %}

    <ul class="pagination justify-content-center">
        {% if equipments.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ equipments.previous_page_number }}">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}
        <li class="page-item">
            <p class="page-link text-muted">
                Page {{ equipments.number }} of {{ equipments.paginator.num_pages }}.
            </p>
        </li>
        {% if equipments.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ equipments.next_page_number }}">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>

{% endblock %}

enter/templates/history.html
{% extends 'storage/layouts/base.html' %}

{% block title %} History {% endblock %}
 
{% block body %}
    <div class="container">    
        <br>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Mon site</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="#">home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'enter:add_category' %}">New Category</a>
                    </li>
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Storage
                      </a>
                      <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'enter:add_equipment' %}">Input</a></li>
                        <li><a class="dropdown-item" href="#">Output</a></li>
                      </ul>
                    </li>
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Inventory
                      </a>
                      <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'enter:screen_equipment' %}">Input</a></li>
                        <li><a class="dropdown-item" href="#">Output</a></li>
                      </ul>
                    </li>
                </ul>
            </div>
        </nav>

        <br>

        <table class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th>user</th>
                    <th>action</th>
                    <th>time</th>
                </tr>
            </thead>
            <tbody>
                {% for equipment in equipments %}
                <tr>
                    <td>{{ equipment.user }}</td>
                    <td>{{ equipment.action }}</td>
                    <td>{{ equipment.timestamp }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block footer %}

<ul class="pagination justify-content-center">
    {% if equipments.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ equipments.previous_page_number }}">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
    {% endif %}
    <li class="page-item">
        <p class="page-link text-muted">
            Page {{ equipments.number }} of {{ equipments.paginator.num_pages }}.
        </p>
    </li>
    {% if equipments.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ equipments.next_page_number }}">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    {% endif %}
</ul>

{% endblock %}